---
# tasks file for Nainterceptor.nginx
- name: "Ensure apache is absent"
  yum: name=httpd state=absent
  when: ansible_distribution == 'CentOS'

- name: "Install nginx package"
  yum: name=nginx state=present
  when: ansible_distribution == 'CentOS'
  notify:
    - "Enable nginx"
    - "Start nginx"

- name: "Prepare directories"
  file: path={{ item.root }} state=directory group=nginx owner=nginx recurse=yes
  with_items: nginx_hosts
  when: ansible_distribution == 'CentOS'

- name: "Configure nginx"
  copy: src=../files/nginx.conf dest=/etc/nginx/nginx.conf owner=nginx
  when: ansible_distribution == 'CentOS'
  notify:
    - "Restart nginx"

- name: "Configure nginx"
  template: src=../files/nginx_site.conf.j2 dest=/etc/nginx/conf.d/{{ item.key }}.conf owner=nginx
  with_items: nginx_hosts
  when: ansible_distribution == 'CentOS'
  notify:
    - "Restart nginx"
